const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "ig@shamimkhan184";
const name = "Name";
const nameHint = "Shamim Khan";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*********";
const retypepass = "Re Type Password";
const forgetPass = "Forget Password";
const login = "Log In";
const signUp = "Sign UP";
const createNewAcc = "or create a new account";
const logInWith = "Log In with";
const privacyPolicy = "Privacy Policy";
const termsNconditions = "Terms and Conditions";
const alreadyHaveAnAcc = "Already have an account?";

const home = "Home", categories = "Categories", cart = "Cart", account = "Account";
